site_name: Clinical Digital Manifesto


theme:
  name: 'material'
  features:
    - navigation.footer
  palette:
    primary: 'grey'
    accent: 'grey'
  font:
    text: 'Poppins'
    code: 'Poppins'
extra_css:
  - stylesheets/extra.css


nav:
  - Welcome: 'welcome.md'
  - The 5 points of our Manifesto: 'manifesto.md'
  - Principles For Working Together To Achieve Our Aims: 'principles.md'
